### ISSUE TITLE
AttributeError: 'VAETracker' object has no attribute 'logg_tensorboard'

### ISSUE THREAD

**Issue by hmkim** [PaccMann/paccmann_omics#4]
Hi!

![스크린샷 2020-11-11 오후 4 30 48](https://user-images.githubusercontent.com/4966343/98782410-45f0a000-243b-11eb-83ef-452013ab2a5a.png)

paccmann_omics of v0.01 have this function (e.g logg_tensorboard)
but in master version there is no function.

https://github.com/PaccMann/paccmann_omics/blob/0.0.1/paccmann_omics/utils/utils.py

Could you check this issue?

Thank you in advance!

**Comment by C-nit** [comment]
This was removed since 0.0.1 because we did not want to implicitly require tensorboard to use the VAETracker.  
If you want to log with tensorboard, you can do it directly in the training script.  

Keep in mind that many changes happen between versions of the package. We do our best to pin the versions for our examples so that they are reproducible.
